#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    if command -v py3compile >/dev/null 2>&1; then
        py3compile -p fotoprint /usr/lib/python3/dist-packages/fotoprint || true
    fi
    command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q /usr/share/applications || true
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor 2>/dev/null || true
fi
exit 0
